// 業種手動指定の選択肢。Google Places APIの有効なPlace Type（Table A）のみ。
// primaryTypeが"service"等の汎用カテゴリで誤認識された場合の上書き用（2026-07-06追加）。
// LBSの対象業種（地域密着の実店舗・士業・専門サービス）を中心に選定。
export const INDUSTRY_OPTIONS: { value: string; label: string }[] = [
  { value: "", label: "自動判定（おまかせ）" },
  { value: "real_estate_agency", label: "不動産" },
  { value: "restaurant", label: "飲食店" },
  { value: "cafe", label: "カフェ" },
  { value: "beauty_salon", label: "美容室・エステ" },
  { value: "hair_salon", label: "理容室・ヘアサロン" },
  { value: "dentist", label: "歯科医院" },
  { value: "doctor", label: "クリニック・医院" },
  { value: "veterinary_care", label: "動物病院" },
  { value: "gym", label: "ジム・フィットネス" },
  { value: "lawyer", label: "法律事務所" },
  { value: "accounting", label: "税理士・会計事務所" },
  { value: "insurance_agency", label: "保険代理店" },
  { value: "car_repair", label: "自動車整備" },
  { value: "car_dealer", label: "自動車販売" },
  { value: "general_contractor", label: "建設・工務店" },
  { value: "electrician", label: "電気工事" },
  { value: "plumber", label: "水道工事" },
  { value: "moving_company", label: "引越し業" },
  { value: "pet_store", label: "ペットショップ" },
  { value: "florist", label: "花屋" },
  { value: "bakery", label: "パン屋" },
  { value: "laundry", label: "クリーニング店" },
  { value: "travel_agency", label: "旅行代理店" },
  { value: "photographer", label: "写真スタジオ" },
  { value: "consultant", label: "コンサルタント" },
];
