// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://beauty.hotpepper.jp
// Generated: 2026-06-06T00:24:34.069Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#4c4c80' | '#333333' | '#000000' | '#444444' | '#ffffff' | '#666666' | '#595959' | '#999999' | '#cdcdcd' | '#bfb4ab' | '#7b7169' | '#e53b4e' | '#463413' | '#f6f6f6' | '#e46c0a' | '#797979' | '#cc4466' | '#dcd6d2' | '#e5848e' | '#f0ebe5' | '#e25983' | '#d43666' | '#0f94d2' | '#0867a9' | '#e0e1e2';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Times' | 'lucida grande';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '900';

export type SpacingToken = '1px' | '18px' | '20px' | '22px' | '25px' | '28px' | '30px' | '32px' | '37px' | '40px' | '140px' | '208px';

export type RadiusToken = '2px' | '5px';

export type DurationToken = never;
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
